<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CountryCodesSeeder extends Seeder
{
    public function run()
    {
        DB::table('ref_country_codes')->truncate();
        $countries = [
            ['country_name' => 'Afghanistan', 'short_code' => 'AF', 'country_code' => '+93'],
            ['country_name' => 'Albania', 'short_code' => 'AL', 'country_code' => '+355'],
            ['country_name' => 'Algeria', 'short_code' => 'DZ', 'country_code' => '+213'],
            ['country_name' => 'Andorra', 'short_code' => 'AD', 'country_code' => '+376'],
            ['country_name' => 'Angola', 'short_code' => 'AO', 'country_code' => '+244'],
            ['country_name' => 'Antigua and Barbuda', 'short_code' => 'AG', 'country_code' => '+1-268'],
            ['country_name' => 'Argentina', 'short_code' => 'AR', 'country_code' => '+54'],
            ['country_name' => 'Armenia', 'short_code' => 'AM', 'country_code' => '+374'],
            ['country_name' => 'Australia', 'short_code' => 'AU', 'country_code' => '+61'],
            ['country_name' => 'Austria', 'short_code' => 'AT', 'country_code' => '+43'],
            ['country_name' => 'Azerbaijan', 'short_code' => 'AZ', 'country_code' => '+994'],
            ['country_name' => 'Bahamas', 'short_code' => 'BS', 'country_code' => '+1-242'],
            ['country_name' => 'Bahrain', 'short_code' => 'BH', 'country_code' => '+973'],
            ['country_name' => 'Bangladesh', 'short_code' => 'BD', 'country_code' => '+880'],
            ['country_name' => 'Barbados', 'short_code' => 'BB', 'country_code' => '+1-246'],
            ['country_name' => 'Belarus', 'short_code' => 'BY', 'country_code' => '+375'],
            ['country_name' => 'Belgium', 'short_code' => 'BE', 'country_code' => '+32'],
            ['country_name' => 'Belize', 'short_code' => 'BZ', 'country_code' => '+501'],
            ['country_name' => 'Benin', 'short_code' => 'BJ', 'country_code' => '+229'],
            ['country_name' => 'Bhutan', 'short_code' => 'BT', 'country_code' => '+975'],
            ['country_name' => 'Bolivia', 'short_code' => 'BO', 'country_code' => '+591'],
            ['country_name' => 'Bosnia and Herzegovina', 'short_code' => 'BA', 'country_code' => '+387'],
            ['country_name' => 'Botswana', 'short_code' => 'BW', 'country_code' => '+267'],
            ['country_name' => 'Brazil', 'short_code' => 'BR', 'country_code' => '+55'],
            ['country_name' => 'Brunei', 'short_code' => 'BN', 'country_code' => '+673'],
            ['country_name' => 'Bulgaria', 'short_code' => 'BG', 'country_code' => '+359'],
            ['country_name' => 'Burkina Faso', 'short_code' => 'BF', 'country_code' => '+226'],
            ['country_name' => 'Burundi', 'short_code' => 'BI', 'country_code' => '+257'],
            ['country_name' => 'Cambodia', 'short_code' => 'KH', 'country_code' => '+855'],
            ['country_name' => 'Cameroon', 'short_code' => 'CM', 'country_code' => '+237'],
            ['country_name' => 'Canada', 'short_code' => 'CA', 'country_code' => '+1'],
            ['country_name' => 'Cape Verde', 'short_code' => 'CV', 'country_code' => '+238'],
            ['country_name' => 'Central African Republic', 'short_code' => 'CF', 'country_code' => '+236'],
            ['country_name' => 'Chad', 'short_code' => 'TD', 'country_code' => '+235'],
            ['country_name' => 'Chile', 'short_code' => 'CL', 'country_code' => '+56'],
            ['country_name' => 'China', 'short_code' => 'CN', 'country_code' => '+86'],
            ['country_name' => 'Colombia', 'short_code' => 'CO', 'country_code' => '+57'],
            ['country_name' => 'Comoros', 'short_code' => 'KM', 'country_code' => '+269'],
            ['country_name' => 'Congo', 'short_code' => 'CG', 'country_code' => '+242'],
            ['country_name' => 'Congo (Democratic Republic)', 'short_code' => 'CD', 'country_code' => '+243'],
            ['country_name' => 'Costa Rica', 'short_code' => 'CR', 'country_code' => '+506'],
            ['country_name' => 'Croatia', 'short_code' => 'HR', 'country_code' => '+385'],
            ['country_name' => 'Cuba', 'short_code' => 'CU', 'country_code' => '+53'],
            ['country_name' => 'Cyprus', 'short_code' => 'CY', 'country_code' => '+357'],
            ['country_name' => 'Czech Republic', 'short_code' => 'CZ', 'country_code' => '+420'],
            ['country_name' => 'Denmark', 'short_code' => 'DK', 'country_code' => '+45'],
            ['country_name' => 'Djibouti', 'short_code' => 'DJ', 'country_code' => '+253'],
            ['country_name' => 'Dominica', 'short_code' => 'DM', 'country_code' => '+1-767'],
            ['country_name' => 'Dominican Republic', 'short_code' => 'DO', 'country_code' => '+1-809'],
            ['country_name' => 'Ecuador', 'short_code' => 'EC', 'country_code' => '+593'],
            ['country_name' => 'Egypt', 'short_code' => 'EG', 'country_code' => '+20'],
            ['country_name' => 'El Salvador', 'short_code' => 'SV', 'country_code' => '+503'],
            ['country_name' => 'Equatorial Guinea', 'short_code' => 'GQ', 'country_code' => '+240'],
            ['country_name' => 'Eritrea', 'short_code' => 'ER', 'country_code' => '+291'],
            ['country_name' => 'Estonia', 'short_code' => 'EE', 'country_code' => '+372'],
            ['country_name' => 'Eswatini', 'short_code' => 'SZ', 'country_code' => '+268'],
            ['country_name' => 'Ethiopia', 'short_code' => 'ET', 'country_code' => '+251'],
            ['country_name' => 'Fiji', 'short_code' => 'FJ', 'country_code' => '+679'],
            ['country_name' => 'Finland', 'short_code' => 'FI', 'country_code' => '+358'],
            ['country_name' => 'France', 'short_code' => 'FR', 'country_code' => '+33'],
            ['country_name' => 'Gabon', 'short_code' => 'GA', 'country_code' => '+241'],
            ['country_name' => 'Gambia', 'short_code' => 'GM', 'country_code' => '+220'],
            ['country_name' => 'Georgia', 'short_code' => 'GE', 'country_code' => '+995'],
            ['country_name' => 'Germany', 'short_code' => 'DE', 'country_code' => '+49'],
            ['country_name' => 'Ghana', 'short_code' => 'GH', 'country_code' => '+233'],
            ['country_name' => 'Greece', 'short_code' => 'GR', 'country_code' => '+30'],
            ['country_name' => 'Grenada', 'short_code' => 'GD', 'country_code' => '+1-473'],
            ['country_name' => 'Guatemala', 'short_code' => 'GT', 'country_code' => '+502'],
            ['country_name' => 'Guinea', 'short_code' => 'GN', 'country_code' => '+224'],
            ['country_name' => 'Guinea-Bissau', 'short_code' => 'GW', 'country_code' => '+245'],
            ['country_name' => 'Guyana', 'short_code' => 'GY', 'country_code' => '+592'],
            ['country_name' => 'Haiti', 'short_code' => 'HT', 'country_code' => '+509'],
            ['country_name' => 'Honduras', 'short_code' => 'HN', 'country_code' => '+504'],
            ['country_name' => 'Hungary', 'short_code' => 'HU', 'country_code' => '+36'],
            ['country_name' => 'Iceland', 'short_code' => 'IS', 'country_code' => '+354'],
            ['country_name' => 'India', 'short_code' => 'IN', 'country_code' => '+91'],
            ['country_name' => 'Indonesia', 'short_code' => 'ID', 'country_code' => '+62'],
            ['country_name' => 'Iran', 'short_code' => 'IR', 'country_code' => '+98'],
            ['country_name' => 'Iraq', 'short_code' => 'IQ', 'country_code' => '+964'],
            ['country_name' => 'Ireland', 'short_code' => 'IE', 'country_code' => '+353'],
            ['country_name' => 'Israel', 'short_code' => 'IL', 'country_code' => '+972'],
            ['country_name' => 'Italy', 'short_code' => 'IT', 'country_code' => '+39'],
            ['country_name' => 'Jamaica', 'short_code' => 'JM', 'country_code' => '+1-876'],
            ['country_name' => 'Japan', 'short_code' => 'JP', 'country_code' => '+81'],
            ['country_name' => 'Jordan', 'short_code' => 'JO', 'country_code' => '+962'],
            ['country_name' => 'Kazakhstan', 'short_code' => 'KZ', 'country_code' => '+7'],
            ['country_name' => 'Kenya', 'short_code' => 'KE', 'country_code' => '+254'],
            ['country_name' => 'Kiribati', 'short_code' => 'KI', 'country_code' => '+686'],
            ['country_name' => 'Korea (North)', 'short_code' => 'KP', 'country_code' => '+850'],
            ['country_name' => 'Korea (South)', 'short_code' => 'KR', 'country_code' => '+82'],
            ['country_name' => 'Kuwait', 'short_code' => 'KW', 'country_code' => '+965'],
            ['country_name' => 'Kyrgyzstan', 'short_code' => 'KG', 'country_code' => '+996'],
            ['country_name' => 'Laos', 'short_code' => 'LA', 'country_code' => '+856'],
            ['country_name' => 'Latvia', 'short_code' => 'LV', 'country_code' => '+371'],
            ['country_name' => 'Lebanon', 'short_code' => 'LB', 'country_code' => '+961'],
            ['country_name' => 'Lesotho', 'short_code' => 'LS', 'country_code' => '+266'],
            ['country_name' => 'Liberia', 'short_code' => 'LR', 'country_code' => '+231'],
            ['country_name' => 'Libya', 'short_code' => 'LY', 'country_code' => '+218'],
            ['country_name' => 'Liechtenstein', 'short_code' => 'LI', 'country_code' => '+423'],
            ['country_name' => 'Lithuania', 'short_code' => 'LT', 'country_code' => '+370'],
            ['country_name' => 'Luxembourg', 'short_code' => 'LU', 'country_code' => '+352'],
            ['country_name' => 'Madagascar', 'short_code' => 'MG', 'country_code' => '+261'],
            ['country_name' => 'Malawi', 'short_code' => 'MW', 'country_code' => '+265'],
            ['country_name' => 'Malaysia', 'short_code' => 'MY', 'country_code' => '+60'],
            ['country_name' => 'Maldives', 'short_code' => 'MV', 'country_code' => '+960'],
            ['country_name' => 'Mali', 'short_code' => 'ML', 'country_code' => '+223'],
            ['country_name' => 'Malta', 'short_code' => 'MT', 'country_code' => '+356'],
            ['country_name' => 'Marshall Islands', 'short_code' => 'MH', 'country_code' => '+692'],
            ['country_name' => 'Mauritania', 'short_code' => 'MR', 'country_code' => '+222'],
            ['country_name' => 'Mauritius', 'short_code' => 'MU', 'country_code' => '+230'],
            ['country_name' => 'Mexico', 'short_code' => 'MX', 'country_code' => '+52'],
            ['country_name' => 'Micronesia', 'short_code' => 'FM', 'country_code' => '+691'],
            ['country_name' => 'Moldova', 'short_code' => 'MD', 'country_code' => '+373'],
            ['country_name' => 'Monaco', 'short_code' => 'MC', 'country_code' => '+377'],
            ['country_name' => 'Mongolia', 'short_code' => 'MN', 'country_code' => '+976'],
            ['country_name' => 'Montenegro', 'short_code' => 'ME', 'country_code' => '+382'],
            ['country_name' => 'Morocco', 'short_code' => 'MA', 'country_code' => '+212'],
            ['country_name' => 'Mozambique', 'short_code' => 'MZ', 'country_code' => '+258'],
            ['country_name' => 'Myanmar', 'short_code' => 'MM', 'country_code' => '+95'],
            ['country_name' => 'Namibia', 'short_code' => 'NA', 'country_code' => '+264'],
            ['country_name' => 'Nauru', 'short_code' => 'NR', 'country_code' => '+674'],
            ['country_name' => 'Nepal', 'short_code' => 'NP', 'country_code' => '+977'],
            ['country_name' => 'Netherlands', 'short_code' => 'NL', 'country_code' => '+31'],
            ['country_name' => 'New Zealand', 'short_code' => 'NZ', 'country_code' => '+64'],
            ['country_name' => 'Nicaragua', 'short_code' => 'NI', 'country_code' => '+505'],
            ['country_name' => 'Niger', 'short_code' => 'NE', 'country_code' => '+227'],
            ['country_name' => 'Nigeria', 'short_code' => 'NG', 'country_code' => '+234'],
            ['country_name' => 'North Macedonia', 'short_code' => 'MK', 'country_code' => '+389'],
            ['country_name' => 'Norway', 'short_code' => 'NO', 'country_code' => '+47'],
            ['country_name' => 'Oman', 'short_code' => 'OM', 'country_code' => '+968'],
            ['country_name' => 'Pakistan', 'short_code' => 'PK', 'country_code' => '+92'],
            ['country_name' => 'Palau', 'short_code' => 'PW', 'country_code' => '+680'],
            ['country_name' => 'Panama', 'short_code' => 'PA', 'country_code' => '+507'],
            ['country_name' => 'Papua New Guinea', 'short_code' => 'PG', 'country_code' => '+675'],
            ['country_name' => 'Paraguay', 'short_code' => 'PY', 'country_code' => '+595'],
            ['country_name' => 'Peru', 'short_code' => 'PE', 'country_code' => '+51'],
            ['country_name' => 'Philippines', 'short_code' => 'PH', 'country_code' => '+63'],
            ['country_name' => 'Poland', 'short_code' => 'PL', 'country_code' => '+48'],
            ['country_name' => 'Portugal', 'short_code' => 'PT', 'country_code' => '+351'],
            ['country_name' => 'Qatar', 'short_code' => 'QA', 'country_code' => '+974'],
            ['country_name' => 'Romania', 'short_code' => 'RO', 'country_code' => '+40'],
            ['country_name' => 'Russia', 'short_code' => 'RU', 'country_code' => '+7'],
            ['country_name' => 'Rwanda', 'short_code' => 'RW', 'country_code' => '+250'],
            ['country_name' => 'Saint Kitts and Nevis', 'short_code' => 'KN', 'country_code' => '+1-869'],
            ['country_name' => 'Saint Lucia', 'short_code' => 'LC', 'country_code' => '+1-758'],
            ['country_name' => 'Saint Vincent and the Grenadines', 'short_code' => 'VC', 'country_code' => '+1-784'],
            ['country_name' => 'Samoa', 'short_code' => 'WS', 'country_code' => '+685'],
            ['country_name' => 'San Marino', 'short_code' => 'SM', 'country_code' => '+378'],
            ['country_name' => 'Sao Tome and Principe', 'short_code' => 'ST', 'country_code' => '+239'],
            ['country_name' => 'Saudi Arabia', 'short_code' => 'SA', 'country_code' => '+966'],
            ['country_name' => 'Senegal', 'short_code' => 'SN', 'country_code' => '+221'],
            ['country_name' => 'Serbia', 'short_code' => 'RS', 'country_code' => '+381'],
            ['country_name' => 'Seychelles', 'short_code' => 'SC', 'country_code' => '+248'],
            ['country_name' => 'Sierra Leone', 'short_code' => 'SL', 'country_code' => '+232'],
            ['country_name' => 'Singapore', 'short_code' => 'SG', 'country_code' => '+65'],
            ['country_name' => 'Slovakia', 'short_code' => 'SK', 'country_code' => '+421'],
            ['country_name' => 'Slovenia', 'short_code' => 'SI', 'country_code' => '+386'],
            ['country_name' => 'Solomon Islands', 'short_code' => 'SB', 'country_code' => '+677'],
            ['country_name' => 'Somalia', 'short_code' => 'SO', 'country_code' => '+252'],
            ['country_name' => 'South Africa', 'short_code' => 'ZA', 'country_code' => '+27'],
            ['country_name' => 'South Sudan', 'short_code' => 'SS', 'country_code' => '+211'],
            ['country_name' => 'Spain', 'short_code' => 'ES', 'country_code' => '+34'],
            ['country_name' => 'Sri Lanka', 'short_code' => 'LK', 'country_code' => '+94'],
            ['country_name' => 'Sudan', 'short_code' => 'SD', 'country_code' => '+249'],
            ['country_name' => 'Suriname', 'short_code' => 'SR', 'country_code' => '+597'],
            ['country_name' => 'Sweden', 'short_code' => 'SE', 'country_code' => '+46'],
            ['country_name' => 'Switzerland', 'short_code' => 'CH', 'country_code' => '+41'],
            ['country_name' => 'Syria', 'short_code' => 'SY', 'country_code' => '+963'],
            ['country_name' => 'Taiwan', 'short_code' => 'TW', 'country_code' => '+886'],
            ['country_name' => 'Tajikistan', 'short_code' => 'TJ', 'country_code' => '+992'],
            ['country_name' => 'Tanzania', 'short_code' => 'TZ', 'country_code' => '+255'],
            ['country_name' => 'Thailand', 'short_code' => 'TH', 'country_code' => '+66'],
            ['country_name' => 'Timor-Leste', 'short_code' => 'TL', 'country_code' => '+670'],
            ['country_name' => 'Togo', 'short_code' => 'TG', 'country_code' => '+228'],
            ['country_name' => 'Tonga', 'short_code' => 'TO', 'country_code' => '+676'],
            ['country_name' => 'Trinidad and Tobago', 'short_code' => 'TT', 'country_code' => '+1-868'],
            ['country_name' => 'Tunisia', 'short_code' => 'TN', 'country_code' => '+216'],
            ['country_name' => 'Turkey', 'short_code' => 'TR', 'country_code' => '+90'],
            ['country_name' => 'Turkmenistan', 'short_code' => 'TM', 'country_code' => '+993'],
            ['country_name' => 'Tuvalu', 'short_code' => 'TV', 'country_code' => '+688'],
            ['country_name' => 'Uganda', 'short_code' => 'UG', 'country_code' => '+256'],
            ['country_name' => 'Ukraine', 'short_code' => 'UA', 'country_code' => '+380'],
            ['country_name' => 'United Arab Emirates', 'short_code' => 'AE', 'country_code' => '+971'],
            ['country_name' => 'United Kingdom', 'short_code' => 'GB', 'country_code' => '+44'],
            ['country_name' => 'United States', 'short_code' => 'US', 'country_code' => '+1'],
            ['country_name' => 'Uruguay', 'short_code' => 'UY', 'country_code' => '+598'],
            ['country_name' => 'Uzbekistan', 'short_code' => 'UZ', 'country_code' => '+998'],
            ['country_name' => 'Vanuatu', 'short_code' => 'VU', 'country_code' => '+678'],
            ['country_name' => 'Vatican City', 'short_code' => 'VA', 'country_code' => '+379'],
            ['country_name' => 'Venezuela', 'short_code' => 'VE', 'country_code' => '+58'],
            ['country_name' => 'Vietnam', 'short_code' => 'VN', 'country_code' => '+84'],
            ['country_name' => 'Yemen', 'short_code' => 'YE', 'country_code' => '+967'],
            ['country_name' => 'Zambia', 'short_code' => 'ZM', 'country_code' => '+260'],
            ['country_name' => 'Zimbabwe', 'short_code' => 'ZW', 'country_code' => '+263'],

            // Add more countries as needed
        ];

        // Insert country data into ref_country_codes table
        DB::table('ref_country_codes')->insert($countries);
        DB::table('ref_country_codes')->whereNotIn('id', [76, 185])->update(['deleted_at' => Carbon::now()]);
    }
}
