<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class RefCptCodesSeeder extends Seeder
{
    public function run()
    {
        DB::table('ref_cpt_codes')->insert([
            ['cpt_code' => '74185', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '73225', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '73725', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '70546', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '73221', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '74181', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '73721', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '70551', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '70553', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '75553', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '72141', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '72156', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '71550', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '70540', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '73720', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '72148', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '72158', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '72196', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '73222', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '76390', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '72146', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '72157', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '70336', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '73220', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '75625', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '75605', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '75630', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '75650', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '75743', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '75724', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '75710', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '76003', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '72295', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '74363', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '75894', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '75984', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '74350', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '74475', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '75860', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '75962', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '75960', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '75827', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '74150', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '74160', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '74150', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '76360', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '72126', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '72125', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '71260', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '71250', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '70481', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '70470', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '70450', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '73701', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '73700', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '72132', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '72131', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '70491', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '72193', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '72192', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '70486', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '72129', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '72128', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '73201', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '73200', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '76700', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '93978', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '76942', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '76645', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '93880', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '76604', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '76705', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '76880', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '7686', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '76770', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '76870', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '76536', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '76830', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '93970', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '93971', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '74020', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '73610', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '74270', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '74280', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '74220', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '74230', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '73650', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '72052', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '72050', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '72040', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '76000', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '71020', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '71010', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '73000', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '73080', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '73550', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '73140', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '73630', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '73090', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '73130', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '73510', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '73060', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '74400', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '73562', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '74000', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '72120', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '72100', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '72170', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '71111', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '71100', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '72220', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '72090', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '73030', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '70220', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '70250', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '74250', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '74249', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '70360', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '71120', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '72072', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '73590', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '73660', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '74246', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '70210', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '73110', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '78075', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '78300', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '78315', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '78320', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '78306', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '78608', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '78607', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '78473', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '78483', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '78465', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '78469', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '78530', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '75809', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '78264', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '78278', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '78223', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '78215', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '78205', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '78580', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '78587', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '78195', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '78290', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => 'G0164', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '78709', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '79000', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '78018', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '78007', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '78802', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '76092', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '76090', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '76091', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '76075', 'description' => null, 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '90785', 'description' => 'Psytx complex interactive', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '90791', 'description' => 'Psych diagnostic evaluation', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '90792', 'description' => 'Psych diag eval w/med srvcs', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '90832', 'description' => 'Psytx pt&/family 30 minutes', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '90833', 'description' => 'Psytx pt&/fam w/e&m 30 min', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '90834', 'description' => 'Psytx pt&/family 45 minutes', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '90836', 'description' => 'Psytx pt&/fam w/e&m 45 min', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '90837', 'description' => 'Psytx pt&/family 60 minutes', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '90838', 'description' => 'Psytx pt&/fam w/e&m 60 min', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '90839', 'description' => 'Psytx crisis initial 60 min', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '90840', 'description' => 'Psytx crisis ea addl 30 min', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '90845', 'description' => 'Psychoanalysis', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '90846', 'description' => 'Family psytx w/o patient', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '90847', 'description' => 'Family psytx w/patient', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '90951', 'description' => 'Esrd serv 4 visits p mo <2yr', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '90952', 'description' => 'Esrd serv 2-3 vsts p mo <2yr', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '90954', 'description' => 'Esrd serv 4 vsts p mo 2-11', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '90955', 'description' => 'Esrd srv 2-3 vsts p mo 2-11', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '90957', 'description' => 'Esrd srv 4 vsts p mo 12-19', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '90966', 'description' => 'Esrd home pt serv p mo 20+', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '90967', 'description' => 'Esrd home pt serv p day <2', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '90968', 'description' => 'Esrd home pt serv p day 2-11', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '90969', 'description' => 'Esrd home pt serv p day 12-19', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '90970', 'description' => 'Esrd home pt serv p day 20+', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '96116', 'description' => 'Neurobehavioral status exam', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '96150', 'description' => 'Assess hlth/behave init', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '96151', 'description' => 'Assess hlth/behave subseq', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '96152', 'description' => 'Intervene hlth/behave indiv', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '96153', 'description' => 'Intervene hlth/behave group', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '96154', 'description' => 'Interv hlth/behav fam w/pt', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '96160', 'description' => 'Pt-focused hlth risk assmt', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '96161', 'description' => 'Caregiver health risk assmt', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '97802', 'description' => 'Medical nutrition indiv in', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '97803', 'description' => 'Med nutrition indiv subseq', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '97804', 'description' => 'Medical nutrition group', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '99201', 'description' => 'Office/outpatient visit new', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '99202', 'description' => 'Office/outpatient visit new', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '99203', 'description' => 'Office/outpatient visit new', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '99204', 'description' => 'Office/outpatient visit new', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '99205', 'description' => 'Office/outpatient visit new', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '99211', 'description' => 'Office/outpatient visit est', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '99212', 'description' => 'Office/outpatient visit est', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '99213', 'description' => 'Office/outpatient visit est', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '99214', 'description' => 'Office/outpatient visit est', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '99215', 'description' => 'Office/outpatient visit est', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '99231', 'description' => 'Subsequent hospital care', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '99232', 'description' => 'Subsequent hospital care', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '99233', 'description' => 'Subsequent hospital care', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '99307', 'description' => 'Nursing fac care subseq', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '99308', 'description' => 'Nursing fac care subseq', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '99309', 'description' => 'Nursing fac care subseq', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '99310', 'description' => 'Nursing fac care subseq', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '99354', 'description' => 'Prolonged service office', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '99355', 'description' => 'Prolonged service office', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '99356', 'description' => 'Prolonged service inpatient', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '99357', 'description' => 'Prolonged service inpatient', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '99406', 'description' => 'Behav chng smoking 3-10 min', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '99407', 'description' => 'Behav chng smoking > 10 min', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '99495', 'description' => 'Trans care mgmt 14 day disch', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '99496', 'description' => 'Trans care mgmt 7 day disch', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '99497', 'description' => 'Advncd care plan 30 min', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => '99498', 'description' => 'Advncd are plan addl 30 min', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => 'G0108', 'description' => 'Diab manage trn per indiv', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => 'G0109', 'description' => 'Diab manage trn ind/group', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => 'G0270', 'description' => 'Mnt subs tx for change dx', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => 'G0296', 'description' => 'Visit to determ ldct elig', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => 'G0396', 'description' => 'Alcohol/subs interv 15-30mn', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => 'G0397', 'description' => 'Alcohol/subs interv >30 min', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => 'G0406', 'description' => 'Inpt/tele follow up 15', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => 'G0407', 'description' => 'Inpt/tele follow up 25', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => 'G0408', 'description' => 'Inpt/tele follow up 35', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => 'G0420', 'description' => 'Ed svc ckd ind per session', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => 'G0421', 'description' => 'Ed svc ckd grp per session', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => 'G0425', 'description' => 'Inpt/ed teleconsult30', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => 'G0426', 'description' => 'Inpt/ed teleconsult50', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => 'G0427', 'description' => 'Inpt/ed teleconsult70', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => 'G0436', 'description' => 'Tobacco-use counsel 3-10 min', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => 'G0437', 'description' => 'Tobacco-use counsel>10min', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => 'G0438', 'description' => 'Ppps, initial visit', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => 'G0439', 'description' => 'Ppps, subseq visit', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => 'G0442', 'description' => 'Annual alcohol screen 15 min', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => 'G0443', 'description' => 'Brief alcohol misuse counsel', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => 'G0444', 'description' => 'Depression screen annual', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => 'G0445', 'description' => 'High inten beh couns std 30m', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => 'G0446', 'description' => 'Intens behave ther cardio dx', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => 'G0447', 'description' => 'Behavior counsel obesity 15m', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => 'G0459', 'description' => 'Telehealth inpt pharm mgmt', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => 'G0506', 'description' => 'Comp asses care plan ccm svc', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => 'G0508', 'description' => 'Crit care telehea consult 60', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => 'G0509', 'description' => 'Crit care telehea consult 50', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => 'G0513', 'description' => 'Prolong prev svcs, first 30m', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => 'G0514', 'description' => 'Prolong prev svcs, addl 30m', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => 'G2086', 'description' => 'Off base opioid tx first m', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => 'G2087', 'description' => 'Off  base opioid tx, sub m', 'created_at' => now(), 'updated_at' => now()],
            ['cpt_code' => 'G2088', 'description' => 'Off opioid tx month add 30', 'created_at' => now(), 'updated_at' => now()],
        ]); 
    }
}