<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RefImagingTestsSeeder extends Seeder
{
    public function run()
    {
         DB::table('ref_imaging_tests')->truncate();
        // First, insert the main categories (sub_of = null)
        $mainCategories = [
            ['name' => 'CT', 'sub_of' => 0,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'MRI', 'sub_of' => 0,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Specials', 'sub_of' => 0,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ultrasound', 'sub_of' => 0,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Radiology', 'sub_of' => 0,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nuclear Medicine', 'sub_of' => 0,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mammography', 'sub_of' => 0,  'created_at' => now(), 'updated_at' => now()],
        ];

        DB::table('ref_imaging_tests')->insert($mainCategories);

        // Get the IDs of the main categories we just inserted
        $ctId = DB::table('ref_imaging_tests')->where('name', 'CT')->first()->id;
        $mriId = DB::table('ref_imaging_tests')->where('name', 'MRI')->first()->id;
        $specialsId = DB::table('ref_imaging_tests')->where('name', 'Specials')->first()->id;
        $ultrasoundId = DB::table('ref_imaging_tests')->where('name', 'Ultrasound')->first()->id;
        $radiologyId = DB::table('ref_imaging_tests')->where('name', 'Radiology')->first()->id;
        $nuclearMedId = DB::table('ref_imaging_tests')->where('name', 'Nuclear Medicine')->first()->id;
        $mammographyId = DB::table('ref_imaging_tests')->where('name', 'Mammography')->first()->id;
        // Now insert all subcategories with proper sub_of references
        DB::table('ref_imaging_tests')->insert([
            // CT subcategories
            ['name' => 'CT Angio SPECIFY:', 'sub_of' => $ctId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'CT Abdomen w/contrast', 'sub_of' => $ctId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'CT Abdomen w/o contrast', 'sub_of' => $ctId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'CT Abdomen/Pelvis w/cont', 'sub_of' => $ctId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'CT Abdomen/Pelvis w/o', 'sub_of' => $ctId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'CT Biopsy', 'sub_of' => $ctId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'CT Cervical w/contrast', 'sub_of' => $ctId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'CT Cervical w/o contrast', 'sub_of' => $ctId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'CT Chest w/contrast', 'sub_of' => $ctId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'CT Chest w/o contrast', 'sub_of' => $ctId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'CT Face, Orbit', 'sub_of' => $ctId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'CT Head w/wo contrast', 'sub_of' => $ctId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'CT Head w/o contrast', 'sub_of' => $ctId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'CT Lower Extremity w/cont.', 'sub_of' => $ctId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'CT Lower Extremity w/o cont', 'sub_of' => $ctId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'CT Lumbar w/contrast', 'sub_of' => $ctId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'CT Lumbar w/o contrast', 'sub_of' => $ctId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'CT Neck w/contrast', 'sub_of' => $ctId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'CT Pelvis w/contrast', 'sub_of' => $ctId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'CT Pelvis w/o contrast', 'sub_of' => $ctId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'CT Sinuses', 'sub_of' => $ctId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'CT Thoracic w/contrast', 'sub_of' => $ctId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'CT Thoracic w/o', 'sub_of' => $ctId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'CT Upper Ext w/contrast', 'sub_of' => $ctId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'CT Upper Ext w/o', 'sub_of' => $ctId,  'created_at' => now(), 'updated_at' => now()],

            // MRI subcategories
            ['name' => 'MRA Abdomen', 'sub_of' => $mriId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'MRA Arm', 'sub_of' => $mriId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'MRA Femoral Art', 'sub_of' => $mriId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'MRA Head/Neck', 'sub_of' => $mriId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'MRA Wrist', 'sub_of' => $mriId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'MRI Abdomen', 'sub_of' => $mriId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'MRI Ankle', 'sub_of' => $mriId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'MRI Brain w/o contrast', 'sub_of' => $mriId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'MRI Brain w/wo contrast', 'sub_of' => $mriId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'MRI Cardiac', 'sub_of' => $mriId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'MRI Cervical w/o contrast', 'sub_of' => $mriId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'MRI Cervical w/wo contrast', 'sub_of' => $mriId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'MRI Chest', 'sub_of' => $mriId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'MRI Elbow', 'sub_of' => $mriId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'MRI Face, Orbit, Neck', 'sub_of' => $mriId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'MRI Knee', 'sub_of' => $mriId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'MRI Lower Extremity', 'sub_of' => $mriId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'MRI Lumbar w/o contrast', 'sub_of' => $mriId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'MRI Lumbar w/wo contrast', 'sub_of' => $mriId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'MRI Pelvis', 'sub_of' => $mriId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'MRI Shoulder', 'sub_of' => $mriId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'MRI Shoulder Arth', 'sub_of' => $mriId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'MRI Spectroscopy', 'sub_of' => $mriId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'MRI Thoracic w/o contrast', 'sub_of' => $mriId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'MRI Thoracic w/wo contrast', 'sub_of' => $mriId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'MRI TMJ', 'sub_of' => $mriId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'MRI Upper Extremity', 'sub_of' => $mriId,  'created_at' => now(), 'updated_at' => now()],

            // Specials subcategories
            ['name' => 'Angio ABD Aortogram', 'sub_of' => $specialsId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Angio Aortic Arch', 'sub_of' => $specialsId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Angio ABD/lliofem', 'sub_of' => $specialsId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Angio ABD/lliofem', 'sub_of' => $specialsId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ango Carotid Bil', 'sub_of' => $specialsId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Angio Carotid', 'sub_of' => $specialsId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Angio Cerebral 4 Vessels', 'sub_of' => $specialsId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Angio Pulm Select', 'sub_of' => $specialsId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Angio Renal Select', 'sub_of' => $specialsId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Angio Renal Select', 'sub_of' => $specialsId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Angio Thoracic Aorta', 'sub_of' => $specialsId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Angio Extremity', 'sub_of' => $specialsId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bx', 'sub_of' => $specialsId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Discogram Lumbar', 'sub_of' => $specialsId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Drain Cath / Tube Change', 'sub_of' => $specialsId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Emboliz', 'sub_of' => $specialsId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gastrostomy Tube Change', 'sub_of' => $specialsId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gastrostomy Tube Insert Perc', 'sub_of' => $specialsId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nephrostomy Tube Change', 'sub_of' => $specialsId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nephrostomy Tube Insert', 'sub_of' => $specialsId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'PICC Line Placement', 'sub_of' => $specialsId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'PTA', 'sub_of' => $specialsId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Renal Vein Renins', 'sub_of' => $specialsId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Stent Placement', 'sub_of' => $specialsId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Superier Vena Cavagram', 'sub_of' => $specialsId,  'created_at' => now(), 'updated_at' => now()],

            // Ultrasound subcategories
            ['name' => 'US Abdomen', 'sub_of' => $ultrasoundId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'US Aorta', 'sub_of' => $ultrasoundId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'US Aspiration', 'sub_of' => $ultrasoundId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'US Breast', 'sub_of' => $ultrasoundId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'US Biopsy', 'sub_of' => $ultrasoundId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'US Carotids', 'sub_of' => $ultrasoundId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'US Chest', 'sub_of' => $ultrasoundId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'US Gallbladder', 'sub_of' => $ultrasoundId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'US Liver', 'sub_of' => $ultrasoundId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'US Paracentesis', 'sub_of' => $ultrasoundId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'US Popliteal', 'sub_of' => $ultrasoundId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'US Pelvis', 'sub_of' => $ultrasoundId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'US Renal', 'sub_of' => $ultrasoundId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'US Scrotum', 'sub_of' => $ultrasoundId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'US Thyroid', 'sub_of' => $ultrasoundId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'US Transvaginal', 'sub_of' => $ultrasoundId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'US Venous Flow Bil', 'sub_of' => $ultrasoundId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'US Venous Flow', 'sub_of' => $ultrasoundId,  'created_at' => now(), 'updated_at' => now()],

            // Radiology subcategories
            ['name' => 'Abdomen Flat & Erect', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ankle', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Barium Enema', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Barium Enema w/air', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Barium Swallow', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Barium Swallow, Modified', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Calcaneus', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cervical Flex-Exten', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cervical Spine 5 View', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cervical Spine AP/Lat', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Chest Fluoro', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Chest PA/Lat', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Chest PA only', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Clavicle', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Elbow', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Femur', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Fingers', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Foot', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Forearm', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hand', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hip', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Humerus', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'IVP', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Knee', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'KUB', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lumbar Flex-Exten', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lumbar Spine 5 View', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lumbar Spine AP/Lat', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Pelvis', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ribs', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ribs', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sacrum/Coccyx', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Scoliosis Survey', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Shoulder', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sinuses', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Skull AP/Lat', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Small Bowel', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Small Bowel & UGI', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Soft Tissue Neck', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sternum', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thoracic Spine AP/Lat', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tibia-Fibula', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Toes', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'UGI', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Waters View Only', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Wrist', 'sub_of' => $radiologyId,  'created_at' => now(), 'updated_at' => now()],

            // Nuclear Medicine subcategories
            ['name' => 'Adrenal Scan', 'sub_of' => $nuclearMedId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bone Scan - Limited', 'sub_of' => $nuclearMedId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bone Scan - 3 Phase', 'sub_of' => $nuclearMedId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bone Scan - Spect', 'sub_of' => $nuclearMedId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bone Scan - Whole Body', 'sub_of' => $nuclearMedId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Brain Scan', 'sub_of' => $nuclearMedId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Brain - Spect', 'sub_of' => $nuclearMedId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cardiac Blood Pool (MUGA)', 'sub_of' => $nuclearMedId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cardiac - Rest/Stress', 'sub_of' => $nuclearMedId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cardiac - Dip Thallium', 'sub_of' => $nuclearMedId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cardiac Infarct Scan', 'sub_of' => $nuclearMedId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'CSF Cysternograrn', 'sub_of' => $nuclearMedId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'CSF Shuntogram', 'sub_of' => $nuclearMedId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gastric Emptying Study', 'sub_of' => $nuclearMedId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gl Blood Scan', 'sub_of' => $nuclearMedId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hepatobiliary Scan (Hidia)', 'sub_of' => $nuclearMedId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hepatobiliary Scan (Hidia) w/CCK', 'sub_of' => $nuclearMedId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Liver / Spleen Scan', 'sub_of' => $nuclearMedId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Liver Scan - Spect', 'sub_of' => $nuclearMedId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lung Scan - Perfusion', 'sub_of' => $nuclearMedId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lung Scan - Ventilation', 'sub_of' => $nuclearMedId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lung Soon - Vent & Perfusion', 'sub_of' => $nuclearMedId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lymph Node Scan', 'sub_of' => $nuclearMedId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Meckels Scan', 'sub_of' => $nuclearMedId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'PET', 'sub_of' => $nuclearMedId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Renal Scan - Function', 'sub_of' => $nuclearMedId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thyroid Therapy', 'sub_of' => $nuclearMedId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thyroid Mets. Whole Body', 'sub_of' => $nuclearMedId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thyroid Imaging w/uptake', 'sub_of' => $nuclearMedId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tumor Local. Whole Body', 'sub_of' => $nuclearMedId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Screening Mammogram', 'sub_of' => $mammographyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Diag Mammogram', 'sub_of' => $mammographyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Diagnostic Mammogram', 'sub_of' => $mammographyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Implants - Mammogram', 'sub_of' => $mammographyId,  'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bone Density', 'sub_of' => $mammographyId, 'created_at' => now(), 'updated_at' => now()],
        ]);
    }
}
