<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class RefRpmDevices extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('ref_rpm_devices')->truncate();
        DB::table('ref_rpm_devices')->insert([
            [
                'id'              => '1',
                'device_uuid'     => Str::random(10),
                'device'          => 'iScale PLUS 12 Months Commercial Membership',
                'one_time_charge' => '100',
                'per_month_amount'=> '50',
                'category'        => 'iScale',
                'sku'             => 'SMiS-12C',
            ],
            [
                'id'              => '2',
                'device_uuid'     => Str::random(10),
                'device'          => 'iPulseOx 12 Months Commercial Membership',
                'one_time_charge' => '100',
                'per_month_amount'=> '50',
                'category'        => 'iPulseOx',
                'sku'             => 'SMiPX-12C',
            ],
            [
                'id'              => '3',
                'device_uuid'     => Str::random(10),
                'device'          => '12-Month Membership: iBloodPressure MultiCuff - XL',
                'one_time_charge' => '100',
                'per_month_amount'=> '50',
                'category'        => 'iBloodPressure',
                'sku'             => 'SMiBP-MCXL-12',
            ],
            [
                'id'              => '4',
                'device_uuid'     => Str::random(10),
                'device'          => '12-Month Membership: iBloodPressure MultiCuff - XXL',
                'one_time_charge' => '100',
                'per_month_amount'=> '50',
                'category'        => 'iBloodPressure',
                'sku'             => 'SMiBP-MCXXL-12',
            ],
            [
                'id'              => '5',
                'device_uuid'     => Str::random(10),
                'device'          => '12-Month Membership: iBloodPressure MultiCuff - Small',
                'one_time_charge' => '100',
                'per_month_amount'=> '50',
                'category'        => 'iBloodPressure',
                'sku'             => 'SMiBP-MCS-12',
            ],
            [
                'id'              => '6',
                'device_uuid'     => Str::random(10),
                'device'          => '12-Month Membership: iGlucose Plus',
                'one_time_charge' => '100',
                'per_month_amount'=> '50',
                'category'        => 'iGlucose',
                'sku'             => 'SMiG-PLUS-12',
            ],
            [
                'id'              => '7',
                'device_uuid'     => Str::random(10),
                'device'          => '4-Month Membership: iGlucose Plus',
                'one_time_charge' => '100',
                'per_month_amount'=> '50',
                'category'        => 'iGlucose',
                'sku'             => 'SMiG-PLUS-04',
            ],
            [
                'id'              => '8',
                'device_uuid'     => Str::random(10),
                'device'          => '12-Month Membership: iBloodPressure MultiCuff - Large',
                'one_time_charge' => '100',
                'per_month_amount'=> '50',
                'category'        => 'iBloodPressure',
                'sku'             => 'SMiBP-MCL-12',
            ],
            [
                'id'              => '9',
                'device_uuid'     => Str::random(10),
                'device'          => 'iBloodPressure Pro 12 Month Commercial Membership',
                'one_time_charge' => '100',
                'per_month_amount'=> '50',
                'category'        => 'iBloodPressure Pro',
                'sku'             => 'SMiBP2.0-12C',
            ],
            [
                'id'              => '10',
                'device_uuid'     => Str::random(10),
                'device'          => 'iScale 12 Month Commercial Membership',
                'one_time_charge' => '100',
                'per_month_amount'=> '50',
                'category'        => 'iScale',
                'sku'             => 'SMiS1.5-12C',
            ],
            [
                'id'              => '11',
                'device_uuid'     => Str::random(10),
                'device'          => 'iBloodPressure MultiCuff - XXL Cuff',
                'one_time_charge' => '100',
                'per_month_amount'=> '50',
                'category'        => 'iBloodPressure',
                'sku'             => 'AC4052-04',
            ],
            [
                'id'              => '12',
                'device_uuid'     => Str::random(10),
                'device'          => 'iBloodPressure MultiCuff - Large Cuff',
                'one_time_charge' => '100',
                'per_month_amount'=> '50',
                'category'        => 'iBloodPressure',
                'sku'             => 'AC2242-41',
            ],
            [
                'id'              => '13',
                'device_uuid'     => Str::random(10),
                'device'          => 'XL Cuff for iBloodPressure Multi-Cuff',
                'one_time_charge' => '100',
                'per_month_amount'=> '50',
                'category'        => 'iBloodPressure',
                'sku'             => 'AC2245-021MC',
            ],
            [
                'id'              => '14',
                'device_uuid'     => Str::random(10),
                'device'          => 'iBloodPressure Classic Cuff - Large',
                'one_time_charge' => '100',
                'per_month_amount'=> '50',
                'category'        => 'iBloodPressure',
                'sku'             => 'AC2242-11',
            ],
            [
                'id'              => '15',
                'device_uuid'     => Str::random(10),
                'device'          => 'FibriCheck',
                'one_time_charge' => '100',
                'per_month_amount'=> '50',
                'category'        => 'Smart Health Solutions',
                'sku'             => 'FIBRICHECK',
            ],
            [
                'id'              => '16',
                'device_uuid'     => Str::random(10),
                'device'          => 'Gestational Diabetes Program',
                'one_time_charge' => '100',
                'per_month_amount'=> '50',
                'category'        => 'iGlucose',
                'sku'             => 'SMiG-PLUS-03GD',
            ],
            [
                'id'              => '17',
                'device_uuid'     => Str::random(10),
                'device'          => 'SmartTouch Engage',
                'one_time_charge' => '100',
                'per_month_amount'=> '50',
                'category'        => 'Smart Health Solutions',
                'sku'             => 'PAT-ENG-STE',
            ],
            [
                'id'              => '18',
                'device_uuid'     => Str::random(10),
                'device'          => 'SmartTouch Consent',
                'one_time_charge' => '100',
                'per_month_amount'=> '50',
                'category'        => 'Smart Health Solutions',
                'sku'             => 'PAT-ENG-STC',
            ],
            [
                'id'              => '19',
                'device_uuid'     => Str::random(10),
                'device'          => 'iGlucose Replacement Power Adapter',
                'one_time_charge' => '100',
                'per_month_amount'=> '50',
                'category'        => 'iGlucose',
                'sku'             => '390-0GM291-100',
            ],
            [
                'id'              => '20',
                'device_uuid'     => Str::random(10),
                'device'          => 'iBloodPressure Classic Cuff - XL',
                'one_time_charge' => '100',
                'per_month_amount'=> '50',
                'category'        => 'iBloodPressure',
                'sku'             => 'AC2245-021',
            ],
            [
                'id'              => '21',
                'device_uuid'     => Str::random(10),
                'device'          => 'Medium Cuff for iBloodPressure Classic',
                'one_time_charge' => '100',
                'per_month_amount'=> '50',
                'category'        => 'iBloodPressure',
                'sku'             => 'AC2232-03',
            ],
            [
                'id'              => '22',
                'device_uuid'     => Str::random(10),
                'device'          => 'iBloodPressure MultiCuff - Small Cuff',
                'one_time_charge' => '100',
                'per_month_amount'=> '50',
                'category'        => 'iBloodPressure',
                'sku'             => 'AC1636-01',
            ],
            [
                'id'              => '23',
                'device_uuid'     => Str::random(10),
                'device'          => 'OneStep',
                'one_time_charge' => '100',
                'per_month_amount'=> '50',
                'category'        => 'Smart Health Solutions',
                'sku'             => 'ONESTEP-01',
            ],
            [
                'id'              => '24',
                'device_uuid'     => Str::random(10),
                'device'          => 'SmartTouch Onboarding',
                'one_time_charge' => '100',
                'per_month_amount'=> '50',
                'category'        => 'Smart Health Solutions',
                'sku'             => 'PAT-ENG-STO',
            ],
            [
                'id'              => '25',
                'device_uuid'     => Str::random(10),
                'device'          => 'iBloodPressure Power Adapter - Open Stock',
                'one_time_charge' => '100',
                'per_month_amount'=> '50',
                'category'        => 'iBloodPressure',
                'sku'             => 'BLJ06L060100P-U',
            ],
            [
                'id'              => '26',
                'device_uuid'     => Str::random(10),
                'device'          => 'Single Patient Use Lancing Device, Single Count',
                'one_time_charge' => '100',
                'per_month_amount'=> '50',
                'category'        => 'iGlucose',
                'sku'             => 'MGLULANCEUS',
            ],
            // Removing duplicate SMiBP2.0-12C entry as it was listed twice in the data
        ]);
    }
}